// This file wraps the generated Nearley parser
// The grammar is generated by: npm run build:parser
// When using @lexer, Nearley automatically tokenizes the input

import { Parser, Grammar } from "nearley";
import grammar from "./gcode.ne";

export class GCodeParser {
  constructor() {}

  private parse(input: string) {
    const parser = new Parser(Grammar.fromCompiled(grammar));

    parser.feed(input.trim());
    const results = parser.finish();

    if (results.length === 0) {
      throw new Error(
        "No parse results - input may be incomplete or invalid"
      );
    }

    if (results.length > 1) {
      console.warn(
        `Ambiguous parse (${results.length} results), returning first result`
      );
    }

    return results[0];
  }

  public parseGcode(input: string) {
    try {
      return this.parse(input);
    } catch (error: any) {
      throw new Error(`G-code parsing error: ${error.message}`);
    }
  }
}
